# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-07 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
